# Generated by Django 4.2.7 on 2026-03-08 18:55

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('excerpt', models.TextField(help_text='Short summary for listings', max_length=300)),
                ('featured_image', models.ImageField(upload_to='archive/entries/')),
                ('image_alt', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='archive/documents/')),
                ('document_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('doc', 'Word Document'), ('txt', 'Text File'), ('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('author_bio', models.TextField(blank=True)),
                ('published_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='Override default canonical URL')),
                ('references', models.TextField(blank=True, help_text='Sources and references')),
                ('citation_text', models.TextField(blank=True, help_text='How to cite this entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Archive entries',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='#8B4513', help_text='Theme color in hex', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='archive/themes/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='archive/entries/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='archive.archiveentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='archiveentry',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.theme'),
        ),
        migrations.CreateModel(
            name='ArchiveDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archiveentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='archiveentry',
            index=models.Index(fields=['slug'], name='archive_arc_slug_2c7855_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveentry',
            index=models.Index(fields=['theme', '-published_date'], name='archive_arc_theme_i_853067_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveentry',
            index=models.Index(fields=['is_featured'], name='archive_arc_is_feat_2e9afe_idx'),
        ),
    ]
