# Generated by Django 4.2.7 on 2026-03-08 18:55

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('file', models.FileField(upload_to='institutional/brochures/')),
                ('cover_image', models.ImageField(upload_to='institutional/brochures/covers/')),
                ('language', models.CharField(default='English', max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_type', models.CharField(choices=[('school', 'K-12 School'), ('university', 'University/College'), ('library', 'Public Library'), ('ngo', 'Non-Profit Organization'), ('corporate', 'Corporate'), ('government', 'Government Agency'), ('other', 'Other')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('number_of_users', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('content_types', models.CharField(help_text="What content they're interested in", max_length=200)),
                ('message', models.TextField()),
                ('additional_requirements', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='institutional/inquiries/')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='website', max_length=50)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Institutional inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_users', models.IntegerField()),
                ('ip_restrictions', models.TextField(blank=True, help_text='Comma-separated IP ranges')),
                ('domain_restrictions', models.TextField(blank=True, help_text='Comma-separated domains')),
                ('total_downloads', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(default='paid', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Activation'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutional.institutionalinquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicensingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('plan_type', models.CharField(choices=[('school', 'K-12 School'), ('university', 'University/College'), ('library', 'Public Library'), ('ngo', 'Non-Profit Organization'), ('corporate', 'Corporate'), ('government', 'Government Agency')], max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.CharField(max_length=200)),
                ('price_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_users', models.IntegerField(default=1)),
                ('max_users', models.IntegerField(default=100, help_text='-1 for unlimited')),
                ('features', models.JSONField(default=dict, help_text='List of included features')),
                ('max_downloads', models.IntegerField(default=-1, help_text='-1 for unlimited')),
                ('max_searches', models.IntegerField(default=-1)),
                ('api_access', models.BooleanField(default=False)),
                ('api_rate_limit', models.IntegerField(default=100, help_text='Requests per minute')),
                ('support_level', models.CharField(choices=[('basic', 'Basic Email Support'), ('priority', 'Priority Email Support'), ('phone', 'Phone Support'), ('dedicated', 'Dedicated Account Manager')], default='basic', max_length=50)),
                ('support_hours', models.CharField(default='Business Hours', max_length=100)),
                ('response_time', models.CharField(default='Within 48 hours', max_length=100)),
                ('training_included', models.BooleanField(default=False)),
                ('training_hours', models.IntegerField(default=0)),
                ('webinar_access', models.BooleanField(default=False)),
                ('custom_reports', models.BooleanField(default=False)),
                ('analytics_dashboard', models.BooleanField(default=False)),
                ('usage_statistics', models.BooleanField(default=True)),
                ('white_label', models.BooleanField(default=False)),
                ('custom_branding', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'plan_type', 'price_per_year'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('archive', 'Archive Entry'), ('product', 'Digital Product')], max_length=50)),
                ('resource_id', models.IntegerField()),
                ('accessed_by', models.CharField(blank=True, help_text='User identifier', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutional.institutionlicense')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='institutionlicense',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutional.licensingplan'),
        ),
        migrations.AddField(
            model_name='institutionalinquiry',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutional.licensingplan'),
        ),
        migrations.AddIndex(
            model_name='institutionalinquiry',
            index=models.Index(fields=['status', '-created_at'], name='institution_status_6f788d_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionalinquiry',
            index=models.Index(fields=['email'], name='institution_email_79db7e_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionalinquiry',
            index=models.Index(fields=['institution_name'], name='institution_institu_2831cd_idx'),
        ),
    ]
