# Generated by Django 4.2.7 on 2026-03-13 13:24

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalbrochure',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='licensingplan',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
