# Generated by Django 4.2.7 on 2026-03-13 13:24

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='auto_reply_message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Auto Reply Message'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Answer'),
        ),
    ]
