# Generated by Django 4.2.7 on 2026-03-08 18:55

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collaboration/categories/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Collaboration categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', ckeditor.fields.RichTextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('artist', 'Visual Artist'), ('designer', 'Designer'), ('writer', 'Writer/Author'), ('musician', 'Musician/Composer'), ('filmmaker', 'Filmmaker'), ('scholar', 'Scholar/Researcher'), ('educator', 'Educator'), ('cultural_practitioner', 'Cultural Practitioner'), ('other', 'Other')], max_length=50)),
                ('creator_name', models.CharField(max_length=100)),
                ('creator_bio', models.TextField()),
                ('creator_email', models.EmailField(max_length=254)),
                ('creator_phone', models.CharField(blank=True, max_length=20)),
                ('creator_website', models.URLField(blank=True)),
                ('creator_location', models.CharField(blank=True, max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.CharField(max_length=300)),
                ('goals', models.TextField(help_text='What do you hope to achieve?')),
                ('inspiration', models.TextField(blank=True, help_text='What inspired this project?')),
                ('proposed_duration', models.CharField(help_text='e.g., 3 months', max_length=100)),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('has_budget', models.BooleanField(default=False)),
                ('budget_details', models.TextField(blank=True)),
                ('funding_request', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='collaboration/proposals/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='collaboration/projects/')),
                ('status', models.CharField(choices=[('proposal', 'Proposal'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('published', 'Published'), ('rejected', 'Rejected')], default='proposal', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaboration.collaborationcategory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collaboration/testimonials/')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaboration.collaborationproject')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('creator_type', models.CharField(choices=[('artist', 'Visual Artist'), ('designer', 'Designer'), ('writer', 'Writer/Author'), ('musician', 'Musician/Composer'), ('filmmaker', 'Filmmaker'), ('scholar', 'Scholar/Researcher'), ('educator', 'Educator'), ('cultural_practitioner', 'Cultural Practitioner'), ('other', 'Other')], max_length=50)),
                ('portfolio_link', models.URLField(help_text='Link to your portfolio or work samples')),
                ('project_idea', models.TextField(help_text='Briefly describe your collaboration idea')),
                ('samples', models.FileField(help_text='Upload work samples (PDF, DOC, Images, or ZIP)', upload_to='collaboration/submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'zip'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collaboration/projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collaboration.collaborationproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='collaborationproject',
            index=models.Index(fields=['status', '-created_at'], name='collaborati_status_2ece0c_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationproject',
            index=models.Index(fields=['category'], name='collaborati_categor_a997b8_idx'),
        ),
    ]
