# Generated by Django 4.2.7 on 2026-03-08 18:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('preview_text', models.CharField(blank=True, help_text='Preview text shown in inbox', max_length=200)),
                ('html_content', ckeditor.fields.RichTextField()),
                ('text_content', models.TextField(blank=True)),
                ('target_all_subscribers', models.BooleanField(default=True)),
                ('target_frequency', models.CharField(blank=True, choices=[('one-time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('target_interests', models.JSONField(blank=True, default=list)),
                ('frequency', models.CharField(choices=[('one-time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='one-time', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('opens_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('unsubscribes_count', models.IntegerField(default=0)),
                ('bounces_count', models.IntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#8B4513', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField()),
                ('recipient_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opens', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('unsubscribes', models.IntegerField(default=0)),
                ('bounces', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='newsletter.newslettercampaign')),
            ],
            options={
                'ordering': ['-issue_number'],
                'unique_together': {('campaign', 'issue_number')},
            },
        ),
        migrations.CreateModel(
            name='NewsletterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.CharField(blank=True, max_length=200)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='newsletter.newsletterissue')),
            ],
            options={
                'ordering': ['-click_count'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='MfalmeBits Newsletter', max_length=100)),
                ('sender_email', models.EmailField(default='newsletter@mfalmebits.com', max_length=254)),
                ('reply_to', models.EmailField(default='noreply@mfalmebits.com', max_length=254)),
                ('require_confirmation', models.BooleanField(default=True)),
                ('double_opt_in', models.BooleanField(default=True)),
                ('welcome_email_subject', models.CharField(default='Welcome to MfalmeBits Newsletter', max_length=200)),
                ('welcome_email_content', ckeditor.fields.RichTextField(blank=True)),
                ('unsubscribe_landing_page', models.TextField(blank=True)),
                ('mailchimp_api_key', models.CharField(blank=True, max_length=100)),
                ('mailchimp_list_id', models.CharField(blank=True, max_length=100)),
                ('sendgrid_api_key', models.CharField(blank=True, max_length=100)),
                ('max_emails_per_hour', models.IntegerField(default=100)),
                ('max_emails_per_day', models.IntegerField(default=1000)),
                ('footer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter settings',
            },
        ),
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML email template')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='newsletter/templates/previews/')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(blank=True, max_length=100)),
                ('unsubscribe_token', models.CharField(max_length=100, unique=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='website', max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='newsletter__email_c1e80c_idx'), models.Index(fields=['is_active', 'confirmed'], name='newsletter__is_acti_f450ee_idx')],
            },
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.newslettertemplate'),
        ),
        migrations.CreateModel(
            name='NewsletterArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
                ('featured_image', models.ImageField(upload_to='newsletter/articles/')),
                ('image_alt', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.newslettercategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('open', 'Opened'), ('click', 'Clicked'), ('unsubscribe', 'Unsubscribed'), ('bounce', 'Bounced')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='newsletter.newsletterissue')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.newsletterlink')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue', 'event_type'], name='newsletter__issue_i_b3ff34_idx'), models.Index(fields=['subscriber', 'event_type'], name='newsletter__subscri_029587_idx')],
            },
        ),
    ]
